spring:
  application:
    name: lifestream

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: true

    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      password: ${REDIS_PASSWORD}

jwt:
  secret:
    key: ${SECRET_KEY}